/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zzeksqdidascmoyqlcps"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZWtzcWRpZGFzY21veXFsY3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNDU0NzYsImV4cCI6MjA3OTkyMTQ3Nn0.znX__P6_M-SoerCE0-lvOS4UiJTEiQjZNUcq5-NTFXk"